**NumPy Exercises :**.

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

In [1]:
import numpy as np

1] Create an array of 10 zeros

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2] Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3] Create an array of 10 fives

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

4] Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5] Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

6] Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr=np.arange(0,9)

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7] Create a 3x3 identity matrix

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8] Use NumPy to generate a random number between 0 and 1


In [15]:
np.random.rand()

0.2354295555419037

9] Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [16]:
np.random.randn(25)

array([ 0.72442172,  0.99238389, -0.07877677, -0.78642623, -1.59535519,
        0.52884782, -0.50485046, -0.94132597, -0.40357288,  1.469745  ,
        0.81942976, -0.24219744, -0.11918187,  0.0467616 , -0.47999651,
       -0.78803645,  0.78497053, -0.4367099 , -0.33553169,  0.63864449,
        0.93359871,  0.97432049, -0.15090743,  0.1563751 , -0.67004545])

10] Create the following matrix:

In [26]:
arr=np.arange(0.01,1.01,0.01)

In [27]:
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [29]:
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

11] Create an array of 20 linearly spaced points between 0 and 1:

In [30]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Numpy Indexing and Selection**

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

1]---------------------------------

In [32]:
arr=np.arange(1,26).reshape(5,5)

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

2]------------------------

In [35]:
arr[3,4]

20

3]---------------------------

In [36]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

4]----------------------------

In [43]:
arr[4:,0:]

array([[21, 22, 23, 24, 25]])

5]-------------------------------

In [44]:
arr[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Now do the following**

1] Get the sum of all the values in mat

In [45]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
arr.sum()

325

In [47]:
np.sum(arr)

325

2] Get the standard deviation of the values in mat

In [48]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
arr.std()

7.211102550927978

3] Get the sum of all the columns in mat

In [50]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
np.sum(arr[0])

15

In [60]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [65]:
np.sum(arr,axis=0)     #sum of all the columns

array([55, 60, 65, 70, 75])

In [66]:
arr.sum(axis=0)        #sum of all the colums

array([55, 60, 65, 70, 75])